apiVersion: v1

kind: Pod

metadata:
  namespace: dev
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: backend-container
      image: redis